[package]
name = "privacy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spartan = "0.7.0"
merlin = "3.0.0"
rand = "0.7.3"
curve25519-dalek = {version = "3.2.0", features = ["serde"]}
